### ISSUE TITLE
Logout doesn't handle bad or dummy Delete request

### ISSUE THREAD

**Issue by gkeishin** [DMTF/python-redfish-library#14]
A couple of inputs on handling the log out:

1. It doesn't throw an error if the session location doesn't exist (Use case where the server is restarted and old session are purged)

2. It allows a user to set any dummy id

As an end user, we would want to know for sure if the session is deleted for real or not. 

Example: 

```
import redfish

robj = redfish.redfish_client(base_url="https://xx.xx.xx.xx/",
                       username="root",
                       password="myPassword",
                       default_prefix='/redfish/v1')
robj.login(auth="session")
robj.set_session_location("dummy")
print("Session location: %s" % robj.get_session_location())
robj.logout()
```

Output:
```
$python sample.py 
Session location: dummy
$
```
It just says worked but on decoding the code how the `logout` handles here is what we should probably handle.

Now, I added debug exception code and response checks in `redfish/rest/v1.py`

Exception:
```
class BadRequestError(Exception):
    """Bad Request to server."""
    pass
```
logout response delete check:
```
            session_loc = self.__session_location.replace(self.__base_url, '')
            print("DEBUG: session_loc: %s" % session_loc)

            resp = self.delete(session_loc)
            # DEBUG: Added Response status check.
            if resp.status != 200:
                print(resp.text)
                raise BadRequestError("HTTP Bad Request"
                                               "return code: %d" % resp.status)
```

```
python sample.py 
Session location: dummy
DEBUG: session_loc: dummy
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

Traceback (most recent call last):
  File "sample.py", line 14, in <module>
    robj.logout()
  File "/usr/local/lib/python2.7/dist-packages/redfish/rest/v1.py", line 893, in logout
    "return code: %d" % resp.status)
redfish.rest.v1.BadRequestError: HTTP Bad Requestreturn code: 400
```

**Comment by jautor** [comment]
@gkeishin could we get you to take that fix and make a pull request for it?

**Comment by gkeishin** [comment]
Sure.. I'll can push up the fix for it..
